openapi: '3.0.3'
info:
  title: netgraph api
  description: netgraph api
  version: 0.0.1
servers:
  - url: http://sample.example.com/
    description: production server
paths:
  /{devices}:
    get:
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    deviceName:
                      type: string
                      description: sample
                    properties:
                      type: object
                      properties:
                        tenant:
                          type: string
                          description: sample
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        '200':
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{\"statusCode\": 200}'
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET, OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
  /switches/{deviceName}:
    get:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
        '500':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false 
        content:
          application/json:
            schema:
              type: object
              properties:
                tenantName:
                  type: string
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              type: object
              properties:
                tenantName:
                  type: string
      responses:
        '200':
          description: sample
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string          
    delete:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
        '500':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        '200':
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{\"statusCode\": 200}'
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE, OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
  /switches/{deviceName}/interfaces:
    get:
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    deviceName:
                      type: string
                      description: sample
                    properties:
                      type: object
                      properties:
                        interfaceType:
                          type: string
                          description: sample
                        interfaceNumber:
                          type: string
                          description: sample
                        tags:
                          type: boolean
                          description: sample
    post:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true 
        description: sample
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  deviceName:
                    type: string
                    description: sample
                  properties:
                    type: object
                    properties:
                      interfaceType:
                        type: string
                        description: sample
                      interfaceNumber:
                        type: string
                        description: sample
                      tags:
                        type: boolean
                        description: sample
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        '200':
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{\"statusCode\": 200}'
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE, OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"