openapi: '3.0.3'
info:
  title: netgraph api
  description: netgraph api
  version: 0.0.1
servers:
  - url: http://sample.example.com/
    description: production server
paths:
  /{devices}:
    get:
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    deviceName:
                      type: string
                      description: sample
                    properties:
                      type: array
                      items:
                        type: object
                        properties:
                          tenant:
                            type: string
                            description: sample
  /switches/{deviceName}:
    get:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
        '400':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false 
        content:
          application/json:
            schema:
              type: object
              properties:
                tenantName:
                  type: string
      responses:
        '200':
          description: sample
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              type: object
              properties:
                tenantName:
                  type: string
      responses:
        '200':
          description: sample
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string          
    delete:
      parameters:
        - name: deviceName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenantName:
                    type: string
        '400':
          description: sample
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
